version: "3"

services:

  mopidy:
    build:
      context: ../mopidyfull
    image: mopidyfull
    ports:
        - "6680:6680"
        - "6600:6600"
    volumes:
        # - fifo:/tmp/snapcast/
        - /tmp/snapcast/:/tmp/snapcast/
        - ./music:/media/music
        - ./mopidydata:/mopidy
        # - ../mopidy/mopidyconfig:/home/mopidy/.config/mopidy

#   snapserver:
#     build:
#       context: ../snapserver
#     image: snapserver
#     ports:
#         - "1704:1704"
#         - "1705:1705"
#         - "1780:1780"
#     volumes:
#         - fifo:/tmp/snapcast/
# volumes:
#   fifo:
